build:
  python: 3.10
  dependencies:
  - ecmwf/ecbuild@develop
  - MathisRosenhauer/libaec@refs/tags/v1.1.3
  - ecmwf/eccodes@develop
  - ecmwf/eckit@feature/eckit-geo
  - ecmwf/atlas@develop
  - ecmwf/mir@feature/eckit-geo
  python_dependencies:
  - ecmwf/eccodes-python@develop
  - ecmwf/earthkit-data@develop
  parallel: 64
  pytest_cmd: |
    pytest --cov=./ --cov-report=xml
    python -m coverage report
